name: zstandard_linux
description: Linux platform implementation of zstandard
version: 1.3.5
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/zstandard/tree/master/zstandard_linux

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  zstandard_platform_interface: ^1.3.5
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^11.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
        pluginClass: ZstandardLinuxPlugin
