name: zstandard
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      # android:
      #   default_package: zstandard_android
      # ios:
      #   default_package: zstandard_ios
      # linux:
      #   default_package: zstandard_linux
      macos:
        default_package: zstandard_macos
      web:
        default_package: zstandard_web
      # windows:
      #   default_package: zstandard_windows

dependencies:
  flutter:
    sdk: flutter
  # zstandard_android: ^6.3.0
  # zstandard_ios: ^6.2.4
  # zstandard_linux: ^3.1.0
  zstandard_macos:
    path: ../zstandard_macos
  zstandard_platform_interface:
    path: ../zstandard_platform_interface
  zstandard_web:
    path: ../zstandard_web
# zstandard_windows: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8
  test: ^1.16.3
