name: zstandard
description: "Flutter plugin to implement Zstandard compression"
version: 1.0.0
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/zstandard

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      # android:
      #   default_package: zstandard_android
      ios:
        default_package: zstandard_ios
      # linux:
      #   default_package: zstandard_linux
      macos:
        default_package: zstandard_macos
      web:
        default_package: zstandard_web
      # windows:
      #   default_package: zstandard_windows

dependencies:
  flutter:
    sdk: flutter
  # zstandard_android: ^6.3.0
  zstandard_ios: ^1.0.0
  # zstandard_linux: ^3.1.0
  zstandard_macos: ^1.0.0
  zstandard_platform_interface: ^1.0.0
  zstandard_web: ^1.0.0
  # zstandard_windows: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8
  test: ^1.16.3
