name: Local file setup
description: Upgrades versions on dependencies and the CHANGELOG.md
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install Landa Messenger CLI
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'bash' }}
      run: npm install @landamessenger/landa-messenger-api -g

    - name: Run read-yaml action
      id: version_data
      uses: jbutcher5/read-yaml@main
      with:
        file: './zstandard_platform_interface/pubspec.yaml'
        key-path: '["version"]'

    - name: Copy CHANGELOG.md to zstandard_platform_interface
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_platform_interface/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_android
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_android/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_ios
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_ios/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_macos
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_macos/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_linux
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_linux/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_windows
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_windows/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_web
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_web/CHANGELOG.md"

    - name: Copy CHANGELOG.md to zstandard_cli
      uses: canastro/copy-file-action@master
      with:
        source: "CHANGELOG.md"
        target: "zstandard_cli/CHANGELOG.md"

    # zstandard
    - name: Update zstandard/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false


    # zstandard_android
    - name: Update zstandard_android/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_android/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard_android/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_android/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false


    # zstandard_ios
    - name: Update zstandard_ios/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_ios/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard_ios/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_ios/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false


    # zstandard_macos
    - name: Update zstandard_macos/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_macos/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard_macos/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_macos/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false

    # zstandard_linux
    - name: Update zstandard_linux/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_linux/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard_linux/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_linux/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false


    # zstandard_windows
    - name: Update zstandard_windows/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_windows/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard_windows/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_windows/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false


    # zstandard_web
    - name: Update zstandard_web/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_web/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false
    - name: Update zstandard_web/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_web/pubspec.yaml'
        propertyPath: 'dependencies.zstandard_platform_interface'
        value: '^${{ steps.version_data.outputs.data }}'
        commitChange: false

    # zstandard_cli
    - name: Update zstandard_cli/pubspec.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'zstandard_cli/pubspec.yaml'
        propertyPath: 'version'
        value: '${{ steps.version_data.outputs.data }}'
        commitChange: false

