name: 📝 Documentation Update
description: Propose changes or improvements to the documentation
title: "<YOUR TITLE HERE>"
labels: ["documentation", "docs", "priority: low"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for what you are proposing.
      options:
        - label: I have searched the existing issues.
          required: true

  - type: markdown
    attributes:
      value: |
        ---

  - type: dropdown
    id: docs_scope
    attributes:
      label: What part of the documentation needs an update?
      multiple: false
      options:
        - README.md
        - Wiki
        - API Documentation
        - Inline Code Comments
        - Other

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    attributes:
      label: Describe the documentation update
      description: |
        Provide a clear and detailed explanation of what should be updated or added.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this update needed?
      description: |
        Explain what issues or gaps this update is addressing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional resources
      description: |
        If you have any external links, references, or examples, include them here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: comments
    attributes:
      label: Additional context or comments
      description: |
        Add any additional context or suggestions related to this documentation update.