name: zstandard_macos
description: macOS platform implementation of zstandard
version: 1.3.24
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/zstandard/tree/master/zstandard_macos

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  zstandard_platform_interface: ^1.3.24
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      macos:
        ffiPlugin: true
        pluginClass: ZstandardMacosPlugin
