name: zstandard_cli
description: CLI implementation of zstandard. For desktops.
version: 1.3.12
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/zstandard/tree/master/zstandard_cli

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.3
  path: ^1.9.1
  platform: ^3.1.6

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^4.0.0
  test: ^1.24.0

platforms:
  linux:
  macos:
  windows:

screenshots:
  - description: 'Windows compression sample'
    path: images/windows_compression_sample.png
  - description: 'Windows decompression sample'
    path: images/windows_decompression_sample.png
  - description: 'macOS compression sample'
    path: images/macos_compression_sample.png
  - description: 'macOS decompression sample'
    path: images/macos_decompression_sample.png
  - description: 'Linux compression sample'
    path: images/linux_compression_sample.png
  - description: 'Linux decompression sample'
    path: images/linux_decompression_sample.png
