name: zstandard_android
description: Android platform implementation of zstandard
version: 1.3.27
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/zstandard/tree/master/zstandard_android

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  zstandard_platform_interface: ^1.3.27
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.landamessenger.zstandard_android
        pluginClass: ZstandardAndroidPlugin
        ffiPlugin: true
