name: zstandard_web
description: Web platform implementation of zstandard
version: 1.0.1
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/zstandard/tree/master/zstandard_web

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: zstandard
    platforms:
      web:
        pluginClass: ZstandardWeb
        fileName: zstandard_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  zstandard_platform_interface: ^1.0.0
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter