name: Git Board Flow - Commit

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  git-board-commits:
    name: Git Board - Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: landamessenger/git-board-flow@master
        with:
          debug: ${{ vars.DEBUG }}
          project-ids: 2
          openrouter-api-key: ${{ secrets.OPEN_ROUTER_API_KEY }}
          openrouter-model: ${{ vars.OPEN_ROUTER_MODEL }}
          token: ${{ secrets.PAT }}