name: Git Board Flow - Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, closed, assigned, unassigned, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  git-board-pull-requests:
    name: Git Board - Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: landamessenger/git-board-flow@v1
        with:
          ai-pull-request-description: true
          ai-ignore-files: build/*
          debug: ${{ vars.DEBUG }}
          openrouter-api-key: ${{ secrets.OPEN_ROUTER_API_KEY }}
          openrouter-model: ${{ vars.OPEN_ROUTER_MODEL }}
          project-ids: 2
          token: ${{ secrets.PAT }}