name: Git Board Flow - Update AI Knowledge

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-ai-knowledge:
    name: Git Board - Update AI Knowledge
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up DOCKER_HOST as output
        id: docker-env
        run: |
          echo "docker_host=unix://${HOME}/.colima/default/docker.sock" >> $GITHUB_OUTPUT

      - name: Update AI knowledge
        uses: landamessenger/git-board-flow@master
        env:
          DOCKER_HOST: ${{ steps.docker-env.outputs.docker_host }}
          RUNNER_TEMP: ${{ github.workspace }}/.runner_temp
        with:
          debug: ${{ vars.DEBUG }}
          ai-ignore-files: build/*
          openrouter-api-key: ${{ secrets.OPEN_ROUTER_API_KEY }}
          openrouter-model: ${{ vars.OPEN_ROUTER_MODEL }}
          project-ids: 2
          single-action: vector_action
          supabase-url: ${{ secrets.SUPABASE_URL }}
          supabase-key: ${{ secrets.SUPABASE_KEY }}
          token: ${{ secrets.PAT }}