name: Push Checks Zstandard

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
      - '!master'
    #paths:
    #  - "zstandard/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  check_zstandard_analyze:
    name: Analyze Zstandard
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard
        run: flutter analyze

  check_zstandard_test:
    name: Test Zstandard
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard
        run: flutter pub get

      - name: Test check
        working-directory: zstandard
        run: flutter test

  check_zstandard_publish_dry_run:
    name: Dry Run Publish Zstandard
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard
        run: dart pub publish --dry-run
