name: Push Checks Windows

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
      - '!master'
    #paths:
    #  - "zstandard_windows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  check_windows_analyze:
    name: Analyze Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard_windows
        shell: cmd
        run: flutter analyze

  check_windows_test:
    name: Test Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

  check_windows_publish_dry_run:
    name: Dry Run Publish Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard_windows
        shell: cmd
        run: dart pub publish --dry-run
