name: Push Checks Windows

on:
  push:
    branches:
      - '**'
      - '!master'
    #paths:
    #  - "zstandard_windows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  check_windows_analyze:
    name: Analyze Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Get dependencies for ${{ env.VERSION }}
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard_windows
        shell: cmd
        run: flutter analyze

  check_windows_test:
    name: Test Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Read version from pubspec.yaml
        working-directory: zstandard_platform_interface
        id: read_version
        shell: cmd
        run: |
          for /f "tokens=2 delims= " %%a in ('findstr "^version: " pubspec.yaml') do set VERSION=%%a
          echo VERSION=%VERSION% >> %GITHUB_ENV%

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

  check_windows_publish_dry_run:
    name: Dry Run Publish Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Read version from pubspec.yaml
        working-directory: zstandard_platform_interface
        id: read_version
        shell: cmd
        run: |
          for /f "tokens=2 delims= " %%a in ('findstr "^version: " pubspec.yaml') do set VERSION=%%a
          echo VERSION=%VERSION% >> %GITHUB_ENV%

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard_windows
        shell: cmd
        run: dart pub publish --dry-run
