name: Push Test Check CLI

on:
  push:
    branches:
      - '**'
      - '!master'
    paths:
      - "zstandard_cli/**"

jobs:
  push_test_check_cli:

    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Landa Messenger CLI
        run: npm install @landamessenger/landa-messenger-api -g

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.24.3'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Test
        working-directory: zstandard_cli
        run: dart test --coverage=coverage

      - name: Prepare coverage
        working-directory: zstandard_cli
        run: dart pub global activate coverage

      - name: Convert coverage to LCOV
        working-directory: zstandard_cli
        run: dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov --in=coverage --out=coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: zstandard_cli/coverage/lcov.info

      - name: Handle job completion
        if: always()
        run: |
          if [ "${{ job.status }}" == "failure" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🔴 Test Failed" \
              --body "${{ github.repository }}: ${{ github.event.head_commit.message }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/push_check_test_cli.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          elif [ "${{ job.status }}" == "cancelled" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟠 Test Canceled" \
              --body "${{ github.repository }}: ${{ github.event.head_commit.message }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/push_check_test_cli.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          else
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟢 Test Passed" \
              --body "${{ github.repository }}: ${{ github.event.head_commit.message }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/push_check_test_cli.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          fi

