name: Push Checks CLI

on:
  push:
    branches:
      - '**'
      - '!master'
    #paths:
    #  - "zstandard_cli/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_cli_analyze:
    name: Analyze CLI
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Landa Messenger CLI
        run: npm install @landamessenger/landa-messenger-api -g

      - name: Read version from pubspec.yml
        working-directory: zstandard_platform_interface
        id: read_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Analyze check
        working-directory: zstandard_cli
        run: dart analyze

      - name: Handle job completion
        if: always()
        run: |
          if [ "${{ job.status }}" == "failure" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🔴 Analyze - CLI Failed" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          elif [ "${{ job.status }}" == "cancelled" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟠 Analyze - CLI Canceled" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          else
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟢 Analyze - CLI Passed" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          fi
  check_cli_test:
    name: Test CLI
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Landa Messenger CLI
        run: npm install @landamessenger/landa-messenger-api -g

      - name: Read version from pubspec.yml
        working-directory: zstandard_platform_interface
        id: read_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Test check
        working-directory: zstandard_cli
        run: dart test

      - name: Handle job completion
        if: always()
        run: |
          if [ "${{ job.status }}" == "failure" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🔴 Test - CLI Failed" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          elif [ "${{ job.status }}" == "cancelled" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟠 Test - CLI Canceled" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          else
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟢 Test - CLI Passed" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          fi



  check_cli_publish_dry_run:
    name: Dry Run Publish CLI
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Landa Messenger CLI
        run: npm install @landamessenger/landa-messenger-api -g

      - name: Read version from pubspec.yml
        working-directory: zstandard_platform_interface
        id: read_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Publish Dry Run
        working-directory: zstandard_cli
        run: dart pub publish --dry-run

      - name: Handle job completion
        if: always()
        run: |
          if [ "${{ job.status }}" == "failure" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🔴 Dry Run Publish - CLI Failed" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          elif [ "${{ job.status }}" == "cancelled" ]; then
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟠 Dry Run Publish - CLI Canceled" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          else
            landa-messenger-api chat-send \
              --id "${{ secrets.CHAT_ID }}" \
              --api_key "${{ secrets.CHAT_KEY }}" \
              --title "🟢 Dry Run Publish - CLI Passed" \
              --body "${{ github.repository }}: v${{ env.VERSION }}" \
              --url "https://github.com/landamessenger/zstandard/actions/workflows/tag_version_and_publish.yml" \
              --image "https://avatars.githubusercontent.com/u/63705403?s=200&v=4" \
              --background_color "#55000000" \
              --text_color "#FFFFFFFF"
          fi
