name: Build CLI

on:
  push:
    branches:
      - master
    # paths:
    #  - "zstandard_cli/**"

jobs:
  prepare_native_precompiled_lib:
    name: Download zstd lib directory
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Landa Messenger CLI
        run: npm install @landamessenger/landa-messenger-api -g

      - name: Download source files from facebook/zstd
        run: |
          cd zstandard_cli
          git clone https://github.com/facebook/zstd.git
          mkdir src
          mv zstd/lib/* src/
          rm -rf zstd/

      - name: List files in zstd/lib to verify
        run: cd zstandard_cli && ls -R src

      - name: Compile x86-x64 macos lib
        run: |
          cd zstandard_cli
          cd builders/macos
          mkdir build_intel && cd build_intel
          cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 ..
          cmake --build . --config Release
          cd ..

      - name: Compile arm64 macos lib
        run: |
          cd zstandard_cli
          cd builders/macos
          mkdir build_arm && cd build_arm
          cmake -DCMAKE_OSX_ARCHITECTURES=arm64 ..
          cmake --build . --config Release
          cd ..