name: Build CLI

on:
  push:
    branches:
      - master
    paths:
      - "zstandard_cli/**"

jobs:
  prepare_macos_precompiled_lib:
    name: Download zstd lib directory
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Landa Messenger CLI
        run: npm install @landamessenger/landa-messenger-api -g

      - name: Download source files from facebook/zstd
        run: |
          cd zstandard_cli
          git clone https://github.com/facebook/zstd.git
          mkdir src
          mv zstd/lib/* src/
          rm -rf zstd/

      - name: List files in zstd/lib to verify
        run: cd zstandard_cli && ls -R src

      - name: Compile x86-x64 macos lib
        run: |
          cd zstandard_cli/builders/macos_intel
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release
          mv libzstandard_macos.dylib ../../../lib/src/bin/libzstandard_macos_intel.dylib
          cd ..
          rm -rf build

      - name: Compile arm64 macos lib
        run: |
          cd zstandard_cli/builders/macos_arm
          mkdir build && cd build
          cmake -DCMAKE_OSX_ARCHITECTURES=arm64 ..
          cmake --build . --config Release
          mv libzstandard_macos.dylib ../../../lib/src/bin/libzstandard_macos_arm.dylib
          cd ..
          rm -rf build

      - name: Verify libs
        run: |
          cd zstandard_cli/lib/src/bin
          lipo -info libzstandard_macos.dylib