name: Push Checks iOS

on:
  push:
    branches:
      - '**'
      - '!master'
    #paths:
    #  - "zstandard_ios/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  check_ios_analyze:
    name: Analyze iOS
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_ios
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard_ios
        run: flutter analyze

  check_ios_test:
    name: Test iOS
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_ios
        run: flutter pub get

      - name: Test check
        working-directory: zstandard_ios
        run: flutter test

  check_ios_publish_dry_run:
    name: Dry Run Publish iOS
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_ios
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard_ios
        run: dart pub publish --dry-run
